import type { Cliente, Nota, Pago, Persona, Proyecto, SerieMensual, Tarea } from "@/types";

export const clientesSeed: Cliente[] = [
  {
    id: "c-001",
    nombre: "Lucía Fernández",
    empresa: "Aurora Studio",
    email: "lucia@aurorastudio.com",
    telefono: "+54 11 5443-2210",
    estado: "activo",
    valor: 8400,
    notas: "Cliente recurrente. Renueva landing cada cuatro meses.",
    creado: "2025-09-12",
  },
  {
    id: "c-002",
    nombre: "Mateo Rivas",
    empresa: "Rivas Inmobiliaria",
    email: "mateo@rivasinmo.com.ar",
    telefono: "+54 351 612-9988",
    estado: "activo",
    valor: 12200,
    notas: "Pidió integración con WhatsApp Business.",
    creado: "2025-08-04",
  },
  {
    id: "c-003",
    nombre: "Camila Ortega",
    empresa: "Verdeóleo",
    email: "camila@verdeoleo.co",
    telefono: "+57 1 322-7741",
    estado: "lead",
    valor: 0,
    notas: "Reunión inicial agendada para el 02/05.",
    creado: "2026-04-12",
  },
  {
    id: "c-004",
    nombre: "Joaquín Méndez",
    empresa: "Méndez Legal",
    email: "joaquin@mendezlegal.com",
    telefono: "+54 11 6712-4408",
    estado: "activo",
    valor: 6500,
    creado: "2025-11-03",
  },
  {
    id: "c-005",
    nombre: "Sofía Beltrán",
    empresa: "Holberton Coffee",
    email: "sofia@holbertoncoffee.com",
    telefono: "+598 99 124 882",
    estado: "lead",
    valor: 0,
    notas: "Quiere e-commerce + landing. Presupuesto enviado.",
    creado: "2026-04-06",
  },
  {
    id: "c-006",
    nombre: "Tomás Aguirre",
    empresa: "Aguirre & Co.",
    email: "tomas@aguirreyco.com.ar",
    telefono: "+54 11 5012-3344",
    estado: "inactivo",
    valor: 3200,
    notas: "Pausó proyecto en febrero. Reabrir en Q3.",
    creado: "2025-06-22",
  },
  {
    id: "c-007",
    nombre: "Valentina Costa",
    empresa: "Costa Wellness",
    email: "valentina@costawellness.com",
    telefono: "+55 11 99812 4502",
    estado: "activo",
    valor: 9800,
    creado: "2026-01-18",
  },
  {
    id: "c-008",
    nombre: "Bruno Salinas",
    empresa: "Salinas Logística",
    email: "bruno@salinaslog.com",
    telefono: "+54 261 488-1102",
    estado: "activo",
    valor: 15400,
    notas: "SaaS interno de tracking. En sprint 3 de 6.",
    creado: "2025-10-29",
  },
  {
    id: "c-009",
    nombre: "Renata Pizzi",
    empresa: "Pizzi Gourmet",
    email: "renata@pizzigourmet.com",
    telefono: "+54 11 4422-8810",
    estado: "lead",
    valor: 0,
    creado: "2026-04-22",
  },
  {
    id: "c-010",
    nombre: "Iván Quiroga",
    empresa: "Quiroga Arquitectura",
    email: "ivan@quirogaarq.com",
    telefono: "+54 11 6090-2415",
    estado: "activo",
    valor: 7100,
    creado: "2025-12-08",
  },
];

export const proyectosSeed: Proyecto[] = [
  {
    id: "p-101",
    clienteId: "c-001",
    titulo: "Landing temporada otoño",
    tipo: "landing",
    estado: "en_progreso",
    precio: 2400,
    fechaInicio: "2026-04-01",
    fechaEntrega: "2026-05-05",
    descripcion: "Landing con catálogo + integración Mailchimp.",
    driveUrl: "",
  },
  {
    id: "p-102",
    clienteId: "c-002",
    titulo: "Portal de propiedades",
    tipo: "saas",
    estado: "en_progreso",
    precio: 9800,
    fechaInicio: "2026-02-15",
    fechaEntrega: "2026-06-30",
    descripcion: "Buscador, filtros, panel admin y CRM básico.",
    driveUrl: "",
  },
  {
    id: "p-103",
    clienteId: "c-004",
    titulo: "Sitio institucional + blog",
    tipo: "landing",
    estado: "finalizado",
    precio: 3100,
    fechaInicio: "2025-11-10",
    fechaEntrega: "2025-12-22",
    driveUrl: "",
  },
  {
    id: "p-104",
    clienteId: "c-007",
    titulo: "Reservas online wellness",
    tipo: "saas",
    estado: "pendiente",
    precio: 7200,
    fechaInicio: "2026-05-02",
    fechaEntrega: "2026-08-15",
    descripcion: "Calendarios, pagos y notificaciones.",
    driveUrl: "",
  },
  {
    id: "p-105",
    clienteId: "c-008",
    titulo: "Tracking interno v2",
    tipo: "saas",
    estado: "en_progreso",
    precio: 15400,
    fechaInicio: "2025-11-01",
    fechaEntrega: "2026-06-10",
    descripcion: "Refactor del dashboard + módulo de reportes.",
    driveUrl: "",
  },
  {
    id: "p-106",
    clienteId: "c-010",
    titulo: "Portfolio interactivo",
    tipo: "landing",
    estado: "finalizado",
    precio: 2900,
    fechaInicio: "2026-01-12",
    fechaEntrega: "2026-02-28",
    driveUrl: "",
  },
  {
    id: "p-107",
    clienteId: "c-001",
    titulo: "Mini-CRM newsletter",
    tipo: "saas",
    estado: "pendiente",
    precio: 4200,
    fechaInicio: "2026-05-15",
    fechaEntrega: "2026-07-20",
    driveUrl: "",
  },
  {
    id: "p-108",
    clienteId: "c-005",
    titulo: "Landing + tienda café",
    tipo: "landing",
    estado: "pendiente",
    precio: 3600,
    fechaInicio: "2026-05-05",
    fechaEntrega: "2026-06-15",
    descripcion: "Aprobación pendiente del presupuesto.",
    driveUrl: "",
  },
];

export const pagosSeed: Pago[] = [
  {
    id: "pg-201",
    clienteId: "c-001",
    proyectoId: "p-101",
    monto: 1200,
    estado: "cobrado",
    metodo: "transferencia",
    fecha: "2026-04-02",
    concepto: "Anticipo 50% landing otoño",
  },
  {
    id: "pg-202",
    clienteId: "c-002",
    proyectoId: "p-102",
    monto: 4900,
    estado: "cobrado",
    metodo: "transferencia",
    fecha: "2026-02-18",
    concepto: "Hito 1 — diseño aprobado",
  },
  {
    id: "pg-203",
    clienteId: "c-002",
    proyectoId: "p-102",
    monto: 4900,
    estado: "pendiente",
    metodo: "transferencia",
    fecha: "2026-05-15",
    concepto: "Hito 2 — entrega beta",
  },
  {
    id: "pg-204",
    clienteId: "c-004",
    proyectoId: "p-103",
    monto: 3100,
    estado: "cobrado",
    metodo: "tarjeta",
    fecha: "2025-12-23",
    concepto: "Pago final sitio institucional",
  },
  {
    id: "pg-205",
    clienteId: "c-008",
    proyectoId: "p-105",
    monto: 5000,
    estado: "cobrado",
    metodo: "transferencia",
    fecha: "2026-03-12",
    concepto: "Sprint 2 — entrega parcial",
  },
  {
    id: "pg-206",
    clienteId: "c-008",
    proyectoId: "p-105",
    monto: 5400,
    estado: "pendiente",
    metodo: "transferencia",
    fecha: "2026-05-10",
    concepto: "Sprint 3 — reportes",
  },
  {
    id: "pg-207",
    clienteId: "c-010",
    proyectoId: "p-106",
    monto: 2900,
    estado: "cobrado",
    metodo: "mercado_pago",
    fecha: "2026-03-01",
    concepto: "Pago final portfolio",
  },
  {
    id: "pg-208",
    clienteId: "c-007",
    proyectoId: "p-104",
    monto: 1800,
    estado: "vencido",
    metodo: "transferencia",
    fecha: "2026-04-15",
    concepto: "Anticipo wellness — vencido",
  },
];

export const personasSeed: Persona[] = [
  { id: "u-damian", nombre: "Damián Cenci", email: "damian@nodaris.io", rol: "Fundador · Estrategia" },
  { id: "u-lucia", nombre: "Lucía Báez", email: "lucia@nodaris.io", rol: "Diseño UI/UX" },
  { id: "u-mateo", nombre: "Mateo Aguirre", email: "mateo@nodaris.io", rol: "Frontend" },
  { id: "u-julieta", nombre: "Julieta Romero", email: "julieta@nodaris.io", rol: "Backend · DevOps" },
  { id: "u-tomas", nombre: "Tomás Ferrer", email: "tomas@nodaris.io", rol: "Project Manager" },
];

export const tareasSeed: Tarea[] = [
  // p-101: Landing temporada otoño (Aurora Studio)
  {
    id: "t-001",
    proyectoId: "p-101",
    titulo: "Wireframes de la landing principal",
    descripcion: "3 variantes con hero, secciones de catálogo y CTA.",
    asignadoA: "u-lucia",
    estado: "finalizado",
    prioridad: "alta",
    fechaVencimiento: "2026-04-08",
    creado: "2026-04-01",
  },
  {
    id: "t-002",
    proyectoId: "p-101",
    titulo: "Integrar Mailchimp con formulario newsletter",
    descripcion: "Doble opt-in y sincronización de tags.",
    asignadoA: "u-mateo",
    estado: "en_progreso",
    prioridad: "media",
    fechaVencimiento: "2026-04-28",
    creado: "2026-04-10",
  },
  {
    id: "t-003",
    proyectoId: "p-101",
    titulo: "Optimización de imágenes y performance",
    asignadoA: "u-mateo",
    estado: "pendiente",
    prioridad: "baja",
    fechaVencimiento: "2026-05-02",
    creado: "2026-04-12",
  },

  // p-102: Portal de propiedades (Rivas Inmobiliaria)
  {
    id: "t-004",
    proyectoId: "p-102",
    titulo: "Diseño del buscador con filtros avanzados",
    descripcion: "Mapa, rango de precios, dormitorios, barrios.",
    asignadoA: "u-lucia",
    estado: "finalizado",
    prioridad: "alta",
    fechaVencimiento: "2026-03-10",
    creado: "2026-02-20",
  },
  {
    id: "t-005",
    proyectoId: "p-102",
    titulo: "Backend: API de propiedades + auth admin",
    asignadoA: "u-julieta",
    estado: "en_progreso",
    prioridad: "alta",
    fechaVencimiento: "2026-05-20",
    creado: "2026-03-01",
  },
  {
    id: "t-006",
    proyectoId: "p-102",
    titulo: "Integración WhatsApp Business para leads",
    descripcion: "Bot que recibe consultas y deriva al asesor.",
    asignadoA: "u-mateo",
    estado: "pendiente",
    prioridad: "media",
    fechaVencimiento: "2026-06-15",
    creado: "2026-04-05",
  },
  {
    id: "t-007",
    proyectoId: "p-102",
    titulo: "Panel admin: ABM de inmuebles y agentes",
    asignadoA: "u-tomas",
    estado: "pendiente",
    prioridad: "alta",
    fechaVencimiento: "2026-06-20",
    creado: "2026-04-08",
  },

  // p-104: Reservas online wellness (Costa Wellness)
  {
    id: "t-008",
    proyectoId: "p-104",
    titulo: "Kickoff y arquitectura del sistema",
    asignadoA: "u-damian",
    estado: "pendiente",
    prioridad: "alta",
    fechaVencimiento: "2026-05-08",
    creado: "2026-04-20",
  },
  {
    id: "t-009",
    proyectoId: "p-104",
    titulo: "Esquema de calendarios + zonas horarias",
    asignadoA: "u-julieta",
    estado: "pendiente",
    prioridad: "media",
    fechaVencimiento: "2026-05-25",
    creado: "2026-04-22",
  },

  // p-105: Tracking interno v2 (Salinas Logística)
  {
    id: "t-010",
    proyectoId: "p-105",
    titulo: "Refactor del dashboard a Server Components",
    asignadoA: "u-mateo",
    estado: "en_progreso",
    prioridad: "alta",
    fechaVencimiento: "2026-05-12",
    creado: "2026-03-15",
  },
  {
    id: "t-011",
    proyectoId: "p-105",
    titulo: "Módulo de reportes exportables (PDF + CSV)",
    descripcion: "Filtros por flota, conductor, fecha y ruta.",
    asignadoA: "u-julieta",
    estado: "en_progreso",
    prioridad: "alta",
    fechaVencimiento: "2026-06-05",
    creado: "2026-04-01",
  },
  {
    id: "t-012",
    proyectoId: "p-105",
    titulo: "Tests E2E del flujo de tracking en vivo",
    asignadoA: "u-julieta",
    estado: "pendiente",
    prioridad: "media",
    fechaVencimiento: "2026-06-08",
    creado: "2026-04-18",
  },

  // p-107: Mini-CRM newsletter (Aurora Studio)
  {
    id: "t-013",
    proyectoId: "p-107",
    titulo: "Definir alcance con Lucía Fernández",
    asignadoA: "u-damian",
    estado: "pendiente",
    prioridad: "media",
    fechaVencimiento: "2026-05-14",
    creado: "2026-04-22",
  },

  // p-108: Landing + tienda café (Holberton Coffee)
  {
    id: "t-014",
    proyectoId: "p-108",
    titulo: "Esperar aprobación del presupuesto",
    descripcion: "Sofía dijo que confirma esta semana.",
    asignadoA: "u-tomas",
    estado: "pendiente",
    prioridad: "baja",
    fechaVencimiento: "2026-05-02",
    creado: "2026-04-23",
  },

  // p-103: Sitio institucional (finalizado)
  {
    id: "t-015",
    proyectoId: "p-103",
    titulo: "Migración de contenido del CMS anterior",
    asignadoA: "u-mateo",
    estado: "finalizado",
    prioridad: "media",
    fechaVencimiento: "2025-12-15",
    creado: "2025-11-12",
  },
];

export const notasSeed: Nota[] = [
  {
    id: "n-001",
    tareaId: "t-001",
    autorId: "u-lucia",
    contenido: "Subí los wireframes al Figma. La tercera variante es la que más se acerca a lo que charlamos con la clienta.",
    fecha: "2026-04-06T14:32:00",
  },
  {
    id: "n-002",
    tareaId: "t-001",
    autorId: "u-damian",
    contenido: "Excelente. Le mando link a Lucía Fernández esta tarde para feedback.",
    fecha: "2026-04-07T09:15:00",
  },
  {
    id: "n-003",
    tareaId: "t-002",
    autorId: "u-mateo",
    contenido: "Configuré el doble opt-in. Falta probar los tags en producción cuando esté la API key final.",
    fecha: "2026-04-22T16:48:00",
  },
  {
    id: "n-004",
    tareaId: "t-005",
    autorId: "u-julieta",
    contenido: "Ya está deployado el endpoint de propiedades. Documentado en /docs/api.md. El auth admin va en sprint 5.",
    fecha: "2026-04-15T11:20:00",
  },
  {
    id: "n-005",
    tareaId: "t-005",
    autorId: "u-mateo",
    contenido: "Le pegué desde el frontend, anda joya. Solo notamos que el orden por precio no respeta nulls — los lista primero.",
    fecha: "2026-04-18T10:05:00",
  },
  {
    id: "n-006",
    tareaId: "t-005",
    autorId: "u-julieta",
    contenido: "Buen catch. Lo arreglo con un NULLS LAST en la query mañana.",
    fecha: "2026-04-18T18:30:00",
  },
  {
    id: "n-007",
    tareaId: "t-010",
    autorId: "u-mateo",
    contenido: "Migrado el 60%. Las cards principales ya son Server Components. Performance mejoró ~35% según Lighthouse.",
    fecha: "2026-04-19T15:42:00",
  },
  {
    id: "n-008",
    tareaId: "t-010",
    autorId: "u-tomas",
    contenido: "Genial. Recordá pasar el changelog para mostrarle a Bruno en la reunión del viernes.",
    fecha: "2026-04-21T08:55:00",
  },
  {
    id: "n-009",
    tareaId: "t-011",
    autorId: "u-julieta",
    contenido: "PDF ya funciona con jsPDF. CSV todavía rompe con caracteres especiales — lo encaro mañana.",
    fecha: "2026-04-23T17:10:00",
  },
  {
    id: "n-010",
    tareaId: "t-014",
    autorId: "u-tomas",
    contenido: "Sofía pidió bajar un poco el alcance del e-commerce. Reagendo reunión para el martes.",
    fecha: "2026-04-24T12:18:00",
  },
];

export const actividadMensual: SerieMensual[] = [
  { mes: "Nov", ingresos: 6800, egresos: 1200, proyectos: 3 },
  { mes: "Dic", ingresos: 9400, egresos: 1500, proyectos: 4 },
  { mes: "Ene", ingresos: 7800, egresos: 1100, proyectos: 3 },
  { mes: "Feb", ingresos: 12200, egresos: 1800, proyectos: 5 },
  { mes: "Mar", ingresos: 14800, egresos: 2100, proyectos: 6 },
  { mes: "Abr", ingresos: 18900, egresos: 2400, proyectos: 7 },
];
